server:
    port: 8888
spring:
  application:
    name: @project.name@
  cloud:
    config:
      server:
        git:
          uri: https://github.com/learnITpossible/spring
    bus:
      trace:
        enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: 123456
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-peer1:8761/eureka/,http://eureka-peer2:8762/eureka/
management:
  security:
    enabled: false
